name = "cobblebanda"
author = "gonzalo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb52cd617d22874bca9d63a13b9ec0ba9b0e2be4db709f2bf872cdd807579698"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/openloader/packs"
