name = "cobblebanda"
author = "gonzalo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "569ca82f52cb23ccc44899e73a03490d97382ae1f26d51ae60b99e36ad56ed6a"

[versions]
fabric = "0.19.5"
minecraft = "1.21.1"

[options]
acceptable-game-versions = ["1.21"]
datapack-folder = "config/openloader/packs"
