# Claves que ops/sync.sh fuerza en server.properties. Las demás quedan como las deja Minecraft.
# online-mode=false: entran amigos sin Minecraft oficial. EasyAuth (/register, /login) evita que alguien entre con
# el nombre de otro y SkinRestorer recupera las skins.
view-distance=10
simulation-distance=6
online-mode=false
motd=§b§lCobblebanda§r §7- Cobblemon 1.8.1
# Semilla elegida: todos los biomas de Alex's Caves a menos de ~2200 bloques del spawn (ver RESEARCH)
level-seed=424242
